---
seed:
  seed: 100
  deterministic: False
  benchmark: True
dataset_dir: ~/dataset/cifar-10/cifar-10-batches-py
num_classes: 10
saved_dir: ./saved_data
storage_dir: ./storage
prefetch: True  # turn on prefetch mode will speedup io
transform:
  pre: null
  train:
    primary:
      random_resize_crop:
        size: 32
        scale: [0.2, 1.0]
        interpolation: 3  # BICUBIC
      random_horizontal_flip:
        p: 0.5
    remaining:
      to_tensor: True
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  test:
    primary: null
    remaining:
      to_tensor: True
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
backdoor:
  poison_ratio: 0.05
  target_label: 3
  blend:
    alpha: 0.1
    trigger_path: ./data/trigger/hello_kitty.png
loader:
  batch_size: 128
  num_workers: 4
  pin_memory: True
network:
  resnet18_cifar:
    num_classes: 10
sync_bn: True  # synchronized batch normalization
criterion:
  cross_entropy:
    reduction: "mean"
optimizer:
  SGD:
    weight_decay: 5.e-4
    momentum: 0.9
    lr: 0.1  # 0.1 * batch_size / 128
lr_scheduler:
  multi_step:
    milestones: [100, 150]
num_epochs: 200